STATCAN_PRODUCT_ID = "32100359"
STATCAN_LANGUAGE = "en"

PROVINCE_STATION_CANDIDATES = {
    "SK": ["REGINA", "SASKATOON"],
    "AB": ["LETHBRIDGE", "CALGARY", "RED DEER"],
    "MB": ["WINNIPEG", "BRANDON"],
    "ON": ["LONDON", "OTTAWA"],
    "QC": ["MONTREAL", "QUEBEC"],
}

YEAR_START = 1995
YEAR_END = 2024

RAW_DATA_DIR = "data/raw"
WEATHER_DIR = f"{RAW_DATA_DIR}/weather"
STATCAN_DIR = f"{RAW_DATA_DIR}/statcan"